### ISSUE TITLE
Morning Session Code Review

### ISSUE THREAD

**Issue by JohnFTitor** [gabyse1/repo-awesome-books#7]
# Hello @MrRamoun and @gabyse1 

Your project has a great design and animations and works as expected. I see you used Bootstrap. 
The logic seems light and maintainable.

## Some suggestions

- [ ] There are some things that I think would make it more readable and light, following the No Repeat Yourself guideline.

https://github.com/gabyse1/repo-awesome-books/blob/da6b613b30213ae1e1c29ab971883789feb8b335/scripts/scroll.js#L9-L37

I think those lines could be replaced for a logic that tracks the "a" tags entirely. You notice that it does the same: remove a class to the link you want to go to and add the class to the others.

- [ ] Add a filter to not add duplicate books

# Closing 😸 

Please let me know If you have any questions about my suggestions. We're all here to learn so let's take advantage of different perspectives!
Cheers and happy coding! 👨🏻‍💻 

<img src="https://media2.giphy.com/media/fT3PPZwB2lZMk/giphy.gif"/>

**Comment by eduardosancho** [comment]
Great job until now, I love the responsive design!

Something weird happened when I added the first books with small titles and authors.
![image](https://user-images.githubusercontent.com/53308506/148961933-3f75208b-a521-48ce-851f-d6f3811b94a8.png)

I believe that issue could be solved by giving a min-width property to the book cards.

Also, consider adding a "success" message after a book is added, or redirect the user to the book list. Otherwise, it's hard to notice changes after you click on "add".
![gif](https://media.giphy.com/media/BS889TAoynmuhj3bvT/giphy.gif)
